services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      TYPEFORM_API_TOKEN: "${TYPEFORM_API_TOKEN:-}"
      PYDANTIC_AI_MODEL: "${PYDANTIC_AI_MODEL:-}"
      OPENAI_API_KEY: "${OPENAI_API_KEY:-}"
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      LOG_FORMAT: "${LOG_FORMAT:-json}"
    volumes:
      - ./xsrc:/app/xsrc  # Hot reload for development

